// src/app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// この行を新しく追加します
import AuthSessionProvider from "@/providers/AuthSessionProvider";

// フォント最適化: display: 'swap'でFOUTを防止、preloadで早期読み込み
const inter = Inter({ 
  subsets: ["latin"],
  display: 'swap', // フォント読み込み中もテキストを表示
  preload: true, // フォントを事前読み込み
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* AuthSessionProviderでchildrenをラップします */}
        <AuthSessionProvider>
          {children}
        </AuthSessionProvider>
      </body>
    </html>
  );
}